### ISSUE TITLE
Automatic pushing of Docker image to DockerHub for releases

### ISSUE THREAD

**Issue by karuppiah7890** [thecasualcoder/dobby#8]
When tagging releases, automatic pushing of Docker image to Docker Hub from Travis CI would be a good feature to have! Especially when PRs are merged, we just need to tag and that's it, it will get released

**Comment by jskswamy** [comment]
Thanks for suggestion @karuppiah7890 , we will work on it soon and release it for ever tag

**Comment by karuppiah7890** [comment]
I could see the code and raise a PR for this. I'll see what I can do this weekend 👍

**Comment by karuppiah7890** [comment]
I tried out pushing the Docker images to Docker Hub from my own repo, using Travis and my Docker Hub account. I found the ways for it to work. Do check out the details and we can choose one way to push it!

Things needed:
1. Docker Hub account access token to authenticate with Docker Hub and to push Docker images
2. Changes in Travis CI to push Docker image
    - Store the secret in CI config yaml if it's going to be stored there
    - Create a [script deployment](https://docs.travis-ci.com/user/deployment/script) and push using a script
3. Script to push Docker image
    - Consider the Docker image tags - latest alone? versioned image alone? or both?
    - Login, build image with tags, push

An alternative way to store the Docker Hub access token is by having it as an environment variable in the travis CI repo settings. It's similar to GitLab CI environment variables

**Comment by karuppiah7890** [comment]
If secret is going to be in Travis CI config, it will look like this -

Docker push script - https://github.com/karuppiah7890/travis-docker-hub-push-demo/blob/master/scripts/docker-push.sh
Travis Config https://github.com/karuppiah7890/travis-docker-hub-push-demo/blob/master/.travis.yml

**Comment by karuppiah7890** [comment]
If secret is going to be in the Travis CI config, it will look like this - 

Travis Config - https://github.com/karuppiah7890/travis-docker-hub-push-demo/blob/8f759acd10476ebf1a323e06bf1a44614ad3a24f/.travis.yml

**Comment by karuppiah7890** [comment]
And it all works, the trial and errors -

https://travis-ci.org/github/karuppiah7890/travis-docker-hub-push-demo
https://hub.docker.com/r/karuppiah7890/dobby
https://hub.docker.com/r/karuppiah7890/dobby/tags (only v3 is there currently)

**Comment by jskswamy** [comment]
@karuppiah7890 could you raise a PR with the working example?

**Comment by nithyanatarajan** [comment]
We have github actions workflow to automate docker image creation on release. Refer [PR](https://github.com/thecasualcoder/dobby/pull/17)
